name: EvoAPI Server Setup
author: EVO Modding
version: 1.3.0
description: |
  Configures server.cfg for EvoAPI, oxmysql, and vMenu.
  Please upload EvoAPI, oxmysql, and vMenu manually to resources/ before running.

tasks:
  - action: write_file
    path: server.cfg
    content: |
      # ===== EVO RP | Powered by EvoAPI =====
      sv_hostname "EVO RP | Powered by EvoAPI"
      sets sv_projectName "EVO RP"
      sets sv_projectDesc "EvoAPI Framework + vMenu Integration"
      sets locale "en-US"
      sets tags "evoapi, roleplay, txadmin"

      # Networking
      endpoint_add_tcp "0.0.0.0:30120"
      endpoint_add_udp "0.0.0.0:30120"

      # Database
      set mysql_connection_string "mysql://root:EVOFILO24@127.0.0.1/evoserver?charset=utf8mb4"

      # Core resources
      ensure oxmysql
      ensure chat
      ensure spawnmanager
      ensure sessionmanager
      ensure basic-gamemode
      ensure hardcap

      # vMenu
      ensure vMenu
      setr vmenu_menu_toggle_key "F1"
      setr vmenu_use_permissions true
      setr vmenu_ban_defaults false

      # EvoAPI
      ensure EvoAPI

      # vMenu permissions generated by EvoAPI
      exec resources/[evo]/EvoAPI/permissions.vmenu.cfg
