$engine: 3
$onesync: on
name: EvoAPI Server Setup
author: EVO Modding
description: Recipe to install EvoAPI, oxmysql, vMenu, and set up server.cfg automatically.

tasks:
  # Download EvoAPI
  - action: download_github
    src: https://github.com/evo-modding/EvoAPI
    ref: main
    dest: ./resources/[evo]/EvoAPI

  # Download oxmysql
  - action: download_github
    src: https://github.com/overextended/oxmysql
    ref: main
    dest: ./resources/[standalone]/oxmysql

  # Download vMenu
  - action: download_github
    src: https://github.com/TomGrobbe/vMenu
    ref: master
    dest: ./resources/[admin]/vMenu

  # Download default EvoAPI server.cfg template
  - action: download_file
    url: https://raw.githubusercontent.com/evo-modding/EvoAPI/main/server.cfg
    path: ./server.cfg
