name: EvoAPI Server Installer
author: EVO Modding
description: >
  Installs EvoAPI v1.3.0 with Web Panel, oxmysql, and vMenu.
  Configures database, permissions, and server.cfg automatically.
version: 1.3.0

tasks:
  - type: download
    description: Downloading EvoAPI Framework (v1.3.0, latest)...
    uri: https://github.com/evo-modding/EvoAPI/archive/refs/heads/main.zip
    path: resources/[evo]/EvoAPI

  - type: download
    description: Installing oxmysql (latest stable)...
    uri: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: resources/[standalone]/oxmysql

  - type: download
    description: Installing vMenu (latest stable)...
    uri: https://github.com/TomGrobbe/vMenu/releases/latest/download/vMenu.zip
    path: resources/[admin]/vMenu

  - type: input
    description: Enter your Discord Webhook URL (leave blank to skip logging):
    variable: discord_webhook

  - type: modify_file
    description: Configuring EvoAPI config.lua with Discord webhook and Web Panel token...
    path: resources/[evo]/EvoAPI/config.lua
    find: Config.DiscordWebhook = ""
    replace: Config.DiscordWebhook = "{{discord_webhook}}"
             Config.WebPanel.Token = "{{random_token}}"

  - type: write_file
    description: Creating optimized starter server.cfg...
    path: server.cfg
    content: |
      # ===== EVO RP | Powered by EvoAPI =====
      sv_hostname "EVO RP | Powered by EvoAPI"
      sets sv_projectName "EVO RP"
      sets sv_projectDesc "EvoAPI Framework + vMenu Integration"
      sets locale "en-US"
      sets tags "evoapi, roleplay, txadmin"

      # Networking
      endpoint_add_tcp "0.0.0.0:30120"
      endpoint_add_udp "0.0.0.0:30120"

      # Database
      set mysql_connection_string "mysql://root:EVOFILO24@127.0.0.1/evoserver?charset=utf8mb4"

      # Core resources
      ensure oxmysql
      ensure chat
      ensure spawnmanager
      ensure sessionmanager
      ensure basic-gamemode
      ensure hardcap

      # vMenu
      ensure vMenu
      setr vmenu_menu_toggle_key "F1"
      setr vmenu_use_permissions true
      setr vmenu_ban_defaults false

      # EvoAPI
      ensure EvoAPI

      # vMenu permissions generated by EvoAPI
      exec resources/[evo]/EvoAPI/permissions.vmenu.cfg

      # ===== EVOAPI Web Panel =====
      # Panel URL: http://<server-ip>:30120/evoapi/panel
      # Token will be printed in the console after install.
