name: EvoAPI Server Installer
author: EVO Modding
version: 1.3.0
description: |
  Installs EvoAPI v1.3.0 with Web Panel, oxmysql, and vMenu.
  Configures database, permissions, and server.cfg automatically.

tasks:
  - action: download
    src: https://github.com/evo-modding/EvoAPI/archive/refs/heads/main.zip
    dest: ./tmp/EvoAPI.zip

  - action: unzip
    src: ./tmp/EvoAPI.zip
    dest: resources/[evo]/EvoAPI

  - action: download
    src: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    dest: ./tmp/oxmysql.zip

  - action: unzip
    src: ./tmp/oxmysql.zip
    dest: resources/[standalone]/oxmysql

  - action: download
    src: https://github.com/TomGrobbe/vMenu/releases/latest/download/vMenu.zip
    dest: ./tmp/vmenu.zip

  - action: unzip
    src: ./tmp/vmenu.zip
    dest: resources/[admin]/vMenu

  - action: write_file
    path: server.cfg
    content: |
      # ===== EVO RP | Powered by EvoAPI =====
      sv_hostname "EVO RP | Powered by EvoAPI"
      sets sv_projectName "EVO RP"
      sets sv_projectDesc "EvoAPI Framework + vMenu Integration"
      sets locale "en-US"
      sets tags "evoapi, roleplay, txadmin"

      # Networking
      endpoint_add_tcp "0.0.0.0:30120"
      endpoint_add_udp "0.0.0.0:30120"

      # Database
      set mysql_connection_string "mysql://root:EVOFILO24@127.0.0.1/evoserver?charset=utf8mb4"

      # Core resources
      ensure oxmysql
      ensure chat
      ensure spawnmanager
      ensure sessionmanager
      ensure basic-gamemode
      ensure hardcap

      # vMenu
      ensure vMenu
      setr vmenu_menu_toggle_key "F1"
      setr vmenu_use_permissions true
      setr vmenu_ban_defaults false

      # EvoAPI
      ensure EvoAPI

      # vMenu permissions generated by EvoAPI
      exec resources/[evo]/EvoAPI/permissions.vmenu.cfg
