$engine: 3
$onesync: on
name: EvoAPI Server Setup
author: EVO Modding
description: One-click installer for EvoAPI, vMenu, oxmysql, and FiveM default resources.

tasks:
  # Download default FiveM base resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources

  # Download EvoAPI
  - action: download_github
    src: https://github.com/evo-modding/EvoAPI
    ref: main
    dest: ./resources/[evo]/EvoAPI

  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./resources/[standalone]/oxmysql.zip

  - action: download_file
    url: https://github.com/TomGrobbe/vMenu/releases/latest/download/vMenu.zip
    path: ./resources/[admin]/vMenu.zip

  # Download EvoAPI default server.cfg template
  - action: download_file
    url: https://raw.githubusercontent.com/evo-modding/EvoAPI/main/server.cfg
    path: ./server.cfg
